# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'analytics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61nalytics.proto\x12\tanalytics\"R\n\nHitRequest\x12\x11\n\tshort_url\x18\x01 \x01(\t\x12\x10\n\x08long_url\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x0c\n\x04hash\x18\x04 \x01(\t\"/\n\x0bHitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1c\n\x0cStatsRequest\x12\x0c\n\x04hash\x18\x01 \x01(\t\"3\n\rStatsResponse\x12\"\n\x05stats\x18\x01 \x03(\x0b\x32\x13.analytics.URLStats\"{\n\x08URLStats\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\x11\n\tshort_url\x18\x02 \x01(\t\x12\x10\n\x08long_url\x18\x03 \x01(\t\x12\x11\n\thit_count\x18\x04 \x01(\x05\x12\x15\n\rlast_accessed\x18\x05 \x01(\x03\x12\x12\n\ncreated_at\x18\x06 \x01(\x03\x32\x8d\x01\n\x10\x41nalyticsService\x12:\n\tRecordHit\x12\x15.analytics.HitRequest\x1a\x16.analytics.HitResponse\x12=\n\x08GetStats\x12\x17.analytics.StatsRequest\x1a\x18.analytics.StatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HITREQUEST']._serialized_start=30
  _globals['_HITREQUEST']._serialized_end=112
  _globals['_HITRESPONSE']._serialized_start=114
  _globals['_HITRESPONSE']._serialized_end=161
  _globals['_STATSREQUEST']._serialized_start=163
  _globals['_STATSREQUEST']._serialized_end=191
  _globals['_STATSRESPONSE']._serialized_start=193
  _globals['_STATSRESPONSE']._serialized_end=244
  _globals['_URLSTATS']._serialized_start=246
  _globals['_URLSTATS']._serialized_end=369
  _globals['_ANALYTICSSERVICE']._serialized_start=372
  _globals['_ANALYTICSSERVICE']._serialized_end=513
# @@protoc_insertion_point(module_scope)
